<a href="https://colab.research.google.com/github/samriddhsingh123/Operation-System-A1/blob/main/COOPRo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [118]:
!pip install numdifftools

In [ ]:

import numdifftools as nd

part 1a

In [139]:
import numdifftools as nd
import numpy as np

alpha=0.1
beta=0.5
t=1
x=[1,-2]
def mainFunction(x):
    abc=x[0]**2
    abd=x[1]**4
    return ((3*(abc))+ abd)
def transpose(X):
    result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]
    return result
def matrixMul(xy,Y):
    X = [[xy[j][i] for j in range(len(xy))] for i in range(len(xy[0]))]
    result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]
    return result

    return a+b
def add(x,temp,delx):
    return np.add(x,temp*delx)
def getGrad(x):
    res=nd.Gradient(ourF)(x).reshape(2,1)
    return res

def ArrayReshape(x):
  return np.array(x).reshape(2,1)
def backTrack(x,temp,delx,eta,grad):
  while(ourF(add(x,temp,delx)) > ourF(x) + eta):
    temp = beta*temp
    xp=alpha*temp
    eta=xp*np.dot(transpose(grad),delx)[0][0]
  t=temp
  f=delx*t
  x=x+f
  grad = getGrad(x)
  delx = -1*grad
  xt=alpha*t
  eta = xt*np.dot(transpose(grad),delx)[0][0]
  return x
  

arr1=[-1,0,0,-1]

grad = getGrad(x)
delx = -1*grad
print(grad)
neg = np.array(arr1).reshape(2,2)
zz=alpha*t
eta = zz*np.dot(transpose(grad),delx)
print(eta)
x=ArrayReshape(x)
count=0
f=eta[0]
eta=f[0]
print(eta)
temp=t
print("BEFORE DESCENT",mainFunction(x))
    
count2=1;
while(count2<2):
  count2=count2+1
  x=backTrack(x,temp,delx,eta,grad) 
  count+=1


print("OUTPUT VALUE: ",mainFunction(x))
print("No of iterations: ", count)
  

[[  6.]
 [-32.]]
[[-106.]]
-106.00000000000006
BEFORE DESCENT [19]
OUTPUT VALUE:  [1.171875]
No of iterations:  1


part b

In [137]:
import numdifftools as nd
import numpy as np

alpha=0.1
beta=0.1
t=1
x=[1,-2]
def mainFunction(x):
    abc=x[0]**2
    abd=x[1]**4
    return ((3*(abc))+ abd)
def transpose(X):
    result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]
    return result
def matrixMul(xy,Y):
    X = [[xy[j][i] for j in range(len(xy))] for i in range(len(xy[0]))]
    result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]
    return result

    return a+b
def add(x,temp,delx):
    return np.add(x,temp*delx)
def getGrad(x):
    res=nd.Gradient(ourF)(x).reshape(2,1)
    return res

def ArrayReshape(x):
  return np.array(x).reshape(2,1)
def backTrack(x,temp,delx,eta,grad):
  while(ourF(add(x,temp,delx)) > ourF(x) + eta):
    temp = beta*temp
    xp=alpha*temp
    eta=xp*np.dot(transpose(grad),delx)[0][0]
  t=temp
  f=delx*t
  x=x+f
  grad = getGrad(x)
  delx = -1*grad
  xt=alpha*t
  eta = xt*np.dot(transpose(grad),delx)[0][0]
  return x
  

arr1=[-1,0,0,-1]

grad = getGrad(x)
delx = -1*grad
print(grad)
neg = np.array(arr1).reshape(2,2)
zz=alpha*t
eta = zz*np.dot(transpose(grad),delx)
print(eta)
x=ArrayReshape(x)
count=0
f=eta[0]
eta=f[0]
print(eta)
temp=t
print("BEFORE DESCENT",mainFunction(x))
    
count2=1;
while(count2<2):
  count2=count2+1
  x=backTrack(x,temp,delx,eta,grad) 
  count+=1


print("OUTPUT VALUE: ",mainFunction(x))
print("No of iterations: ", count)
  

[[  6.]
 [-32.]]
[[-106.]]
-106.00000000000006
BEFORE DESCENT [19]
OUTPUT VALUE:  [2.5536]
No of iterations:  1


partc

In [140]:
def ourF(x):
    abc=x[0]**2
    abd=x[1]**4
    return ((3*(abc))+ abd)
def hessInv(x):
  p=np.array([6,0,0,12*(x**2)]).reshape(2,2)
  p=np.linalg.inv(p)
  return p
x=[1,-2]
grad = nd.Gradient(ourF)([1,-2]).reshape(2,1)
def transpose(X):
    result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]
    return result
def matrixMul(xy,Y):
    X = [[xy[j][i] for j in range(len(xy))] for i in range(len(xy[0]))]
    result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]
    return result

    return a+b
def add(x,temp,delx):
    return np.add(x,temp*delx)
def getGrad(x):
    res=nd.Gradient(ourF)(x).reshape(2,1)
    return res
delx = -1*grad
delxnt = np.dot((-1*hessInv(x[1])),grad)
lsqr = np.dot(transpose(grad), (np.dot(hessInv(x[1]), grad)))[0][0]
count=0
t=1
b=0.5
a=0.1
temp=t
eta = a*temp*np.dot(transpose(grad),delxnt)[0][0]

x=np.array([1,-2]).reshape(2,1)
cc=1
while(cc<2):
  cc=cc+1
 
  
  while(ourF((x+temp*(delxnt))) > ourF(x) + eta):
   

    temp = b*temp
    eta=a*temp*np.dot(transpose(grad),delxnt)[0][0]
  
  t=temp
 
  x=x+t*delxnt
  grad = nd.Gradient(ourF)(x).reshape(2,1)
  delx = -1*grad

  delxnt = np.matmul(-1*hessInv(x[1][0]),grad)
  
  lsqr = np.matmul(np.transpose(grad), (np.matmul(hessInv(x[1][0]), grad)))[0][0]
  eta = a*t*np.matmul(np.transpose(grad),delxnt)[0][0]
  count+=1

opt=x.reshape(2,1)
print(opt,"Optimal point")
print(ourF(opt), "Final output")
print(count,"Number of iterations")

[[-2.22044605e-16]
 [-1.33333333e+00]] Optimal point
[3.16049383] Final output
1 Number of iterations


PartD
gradient descent method

In [141]:
import numdifftools as nd
import numpy as np

alpha=0.1
beta=0.5
t=1
x=[1,-2]
def mainFunction(x):
    abc=x[0]**2
    abd=x[1]**4
    return ((3*(abc))+ abd)
def transpose(X):
    result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]
    return result
def matrixMul(xy,Y):
    X = [[xy[j][i] for j in range(len(xy))] for i in range(len(xy[0]))]
    result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]
    return result

    return a+b
def add(x,temp,delx):
    return np.add(x,temp*delx)
def getGrad(x):
    res=nd.Gradient(ourF)(x).reshape(2,1)
    return res

def ArrayReshape(x):
  return np.array(x).reshape(2,1)
def backTrack(x,temp,delx,eta,grad):
  while(ourF(add(x,temp,delx)) > ourF(x) + eta):
    temp = beta*temp
    xp=alpha*temp
    eta=xp*np.dot(transpose(grad),delx)[0][0]
  t=temp
  f=delx*t
  x=x+f
  grad = getGrad(x)
  delx = -1*grad
  xt=alpha*t
  eta = xt*np.dot(transpose(grad),delx)[0][0]
  return x
  

arr1=[-1,0,0,-1]

grad = getGrad(x)
delx = -1*grad
print(grad)
neg = np.array(arr1).reshape(2,2)
zz=alpha*t
eta = zz*np.dot(transpose(grad),delx)
print(eta)
x=ArrayReshape(x)
count=0
f=eta[0]
eta=f[0]
print(eta)
temp=t
print("BEFORE DESCENT",mainFunction(x))
    
while((grad[0]**2 + grad[1]**2)**(1/2)>0.2):
  t=1
  temp=t
  while(ourF(add(x,temp,delx)) > ourF(x) + eta):
    temp = beta*temp
    xp=alpha*temp
    eta=xp*np.dot(transpose(grad),delx)[0][0]
  t=temp
  f=delx*t
  x=x+f
  grad = getGrad(x)
  delx = -1*grad
  xt=alpha*t
  eta = xt*np.dot(transpose(grad),delx)[0][0]
  
  count+=1


print("OUTPUT VALUE: ",mainFunction(x))
print("No of iterations: ", count)
  

[[  6.]
 [-32.]]
[[-106.]]
-106.00000000000006
BEFORE DESCENT [19]
OUTPUT VALUE:  [0.00114441]
No of iterations:  6


Newton descent method.

In [142]:

def hessInv(x):
  p=np.array([6,0,0,12*(x**2)]).reshape(2,2)
  p=np.linalg.inv(p)
  return p
def mainFunction(x):
    abc=x[0]**2
    abd=x[1]**4
    return ((3*(abc))+ abd)
def transpose(X):
    result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]
    return result
def matrixMul(xy,Y):
    X = [[xy[j][i] for j in range(len(xy))] for i in range(len(xy[0]))]
    result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]
    return result

    return a+b
def add(x,temp,delx):
    return np.add(x,temp*delx)
def getGrad(x):
    res=nd.Gradient(ourF)(x).reshape(2,1)
    return res

def ArrayReshape(x):
  return np.array(x).reshape(2,1)
def backTrack(x,temp,delx,eta,grad):
  while(ourF(add(x,temp,delx)) > ourF(x) + eta):
    temp = beta*temp
    xp=alpha*temp
    eta=xp*np.dot(transpose(grad),delx)[0][0]
  t=temp
  f=delx*t
  x=x+f
  grad = getGrad(x)
  delx = -1*grad
  xt=alpha*t
  eta = xt*np.dot(transpose(grad),delx)[0][0]
  return x
t=1
b=0.5
a=0.1
x=[1,-2]
grad = getGrad(x)
delx = -1*grad
getinverse=-1*hessInv(x[1])
delxnt = np.dot((getinverse),grad)
lsqr = np.dot(transpose(grad), (np.dot(hessInv(x[1]), grad)))[0][0]
count=0

temp=t
eta = a*temp*np.dot(transpose(grad),delxnt)[0][0]

x=ArrayReshape([1,-2])
while(lsqr/2 > 0.001 ):
 
  
  while(ourF((x+temp*(delxnt))) > ourF(x) + eta):
   

    temp = b*temp
    eta=a*temp*np.dot(transpose(grad),delxnt)[0][0]
  
  t=temp
 
  x=x+t*delxnt
  grad = nd.Gradient(ourF)(x).reshape(2,1)
  delx = -1*grad

  delxnt = np.matmul(-1*hessInv(x[1][0]),grad)
  
  lsqr = np.matmul(np.transpose(grad), (np.matmul(hessInv(x[1][0]), grad)))[0][0]
  eta = a*t*np.matmul(np.transpose(grad),delxnt)[0][0]
  count+=1

opt=x.reshape(2,1)
print(opt,"Optimal point")
print(ourF(opt), "Final output")
print(count,"Number of iterations")

[[ 4.93038066e-32]
 [-1.75582990e-01]] Optimal point
[0.00095045] Final output
6 Number of iterations


In this we can see that newton gradient descent give much better optimal value than gradient descent in 6 iterations.

Question2


In [143]:

import math
def f3d(input):
  a=math.exp(input[0]) + 2*(input[1]**2) + 3*(input[2]**2)
  return a

In [144]:

A= np.array([[1,0,-5],[0,1,1],[0,0,0]])
A.shape

(3, 3)

In [180]:
def hessf3d(input):
  p=np.array([[math.exp(input[0]),0,0],[0,4,0],[0,0,6]])
  return p
A= np.array([[1,0,-5],[0,1,1],[0,0,0]])
def transpose(X):
    result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]
    return result
def matrixMul(xy,Y):
    X = [[xy[j][i] for j in range(len(xy))] for i in range(len(xy[0]))]
    result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]
    return result

    return a+b
def add(x,temp,delx):
    return np.add(x,temp*delx)
def getGrad(x):
    res=nd.Gradient(ourF)(x).reshape(2,1)
    return res
def kktMat(input):
  k = np.zeros(25).reshape(5,5)
  i=0
  while(i <3):
    j=0
    while(j <3):
      k[i][j] = hessf3d(input)[i][j]
      j=j+1
    i=i+1
  i=0
  while(i<3):
    j=3
    while(j<5):
      k[i][j] = np.transpose(A)[i][j-3]
      j=j+1
    i=i+1
  i=3
  while(i<5):
    j=0
    while(j<3):
      k[i][j] = A[i-3][j]
      j=j+1
    i=i+1

  i=3
  while(i<5):
    j=3
    while(j<5):
      k[i][j]=0
      j=j+1
    i=i+1
  return np.linalg.inv(k)
  



(3,)

In [181]:
import numpy as np
def transpose(X):
    result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]
    return result
def matrixMul(xy,Y):
    X = [[xy[j][i] for j in range(len(xy))] for i in range(len(xy[0]))]
    result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]
    return result

    return a+b
def add(x,temp,delx):
    return np.add(x,temp*delx)
def getGrad(x):
    res=nd.Gradient(ourF)(x).reshape(2,1)
    return res
x=np.array([1,4,0]).reshape(3,1)
kktMat(x)
rhs = np.zeros(5).reshape(5,1)
grad = nd.Gradient(f3d)(x).reshape(3,1)
delx = -1*grad
for i in range(0,3):
  rhs[i][0] = -1*nd.Gradient(f3d)(x)[i]
rhs[3][0]=0
rhs[4][0]=0
dx = np.zeros(3).reshape(3,1)
for i in range(0,3):
  dx[i] = np.matmul(kktMat(x),rhs)[i][0]
# delxnt = np.matmul((-1*hessInv(x[1])),grad)
mag = -1*np.matmul(np.transpose(grad), dx)

print(mag)

[[0.07441675]]


In [147]:

nd.Gradient(f3d)(x).shape


(3,)

In [183]:
import numpy as np
def transpose(X):
    result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]
    return result
def matrixMul(xy,Y):
    X = [[xy[j][i] for j in range(len(xy))] for i in range(len(xy[0]))]
    result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]
    return result

    return a+b
def add(x,temp,delx):
    return np.add(x,temp*delx)
def getGrad(x):
    res=nd.Gradient(ourF)(x).reshape(2,1)
    return res

count=0
t=1
b=0.5
a=0.1
temp=t
eta = a*temp*np.matmul(np.transpose(grad),dx)[0][0]

while((mag) > 0.01 ):
  if(count >100):
    break
  while(f3d((x+temp*(dx))) > f3d(x) + eta):
   
    print(f3d(x+temp*dx), " f3d(x+temp*dx)")
    print(f3d(x), " f2d(x)")
  
    print(eta, " ETA")
    print(dx, " Newt Dir")
    print(temp, "Step size")
    temp = b*temp
    eta=a*temp*np.matmul(np.transpose(grad),dx)[0][0]
  
  t=temp
  print(mag, " mag")
  print(t, "Value of t changed")
  print(dx, " Newt Dir before x update")
  x=x+t*dx
  grad = nd.Gradient(f3d)(x).reshape(3,1)
  # dx = np.array([1,-1,1/5]).reshape(3,1)
  for i in range(0,3):
    rhs[i][0] = -1*grad[i]
  rhs[3][0]=0
  rhs[4][0]=0
  dx = np.zeros(3).reshape(3,1)
  for i in range(0,3):
    dx[i] = np.matmul(kktMat(x),rhs)[i][0]
  print(dx, "UPDATES DESCENT DIRECTION")
  print(x, " updated value of input")
  print(f3d(x+temp*dx), " ourF(x+temp*dx)")
  print(f3d(x), " ourF(x)")

  
  mag = -1*np.matmul(np.transpose(grad), dx)[0][0]
  eta=a*temp*np.matmul(np.transpose(grad),dx)[0][0]
  # print(grad[0],grad[1], "GRADIENT")
  count+=1

opt=x.reshape(3,1)
print(opt,"Optimal point")
print(f3d(opt), "Final output")
print(count,"Number of iterations")

[[1.15448192]
 [3.96910362]
 [0.03089638]] Optimal point
[34.68281023] Final output
0 Number of iterations
